### ISSUE TITLE
Index URLs in search

### ISSUE THREAD

**Issue by AndrewLorente** [calagator/calagator#146] opened 2014-07-26 22:41 UTC
There's a skipped test in spec/models/event_search_spec.rb that actually seems to be a feature request, so I'm moving it into an issue.

```Ruby
    it "searches event urls by substring" do
      skip "figure how to implement selective substring matching in Sunspot"
      event1 = FactoryGirl.create(:event, url: "http://example.com/wtfbbq.html")
      event2 = FactoryGirl.create(:event, url: "http://example.com/zomg.html")
      Event.search("zomg").should == [event2]
    end
```

**Comment by shawnacscott** [comment] 2015-03-22 23:27
Duplicate of #190

**Closed by shawnacscott** 2015-03-22 23:27 UTC
Labels: feature, search
