### ISSUE TITLE
Meetup import error

### ISSUE THREAD

**Issue by turoczy** [calagator/calagator#595] opened 2019-09-13 19:49 UTC
Just got the following error on a Meetup import. https://d.pr/free/i/evjG1T

It throws the error for both https:// and http://

Content: "ERROR: Unable to import: Unknown error: 401 Unauthorized: {"details":"API requests must be key-signed, oauth-signed, or accompanied by a key: https:\/\/www.meetup.com\/meetup_api\/docs\/#authentication","code":"not_authorized","problem":"You are not authorized to make that request"}"

**Comment by aeschright** [comment] 2021-12-22 23:38
Closing as duplicate of #593

**Closed by aeschright** 2021-12-22 23:38 UTC
