### ISSUE TITLE
Roll back changes not working

### ISSUE THREAD

**Issue by aeschright** [calagator/calagator#295] opened 2015-01-26 00:40 UTC
When I click the "roll back" button on a change at http://calagator.org/changes, it does not appear to work.

**Comment by davidcelis** [comment] 2015-02-03 23:54
Hmm, I was just able to successfully roll back an event deletion (oops)... Which change were you trying to roll back? Does it still not work?

**Comment by aeschright** [comment] 2015-02-05 00:50
I was having trouble specifically with reverting edits to the event title and possibly the tags (I think there may be some additional change tracking issues around the tag system though). I'll give it a try again later, not on the live site. :)

**Comment by shawnacscott** [comment] 2015-03-22 06:09
Closing as possible duplicate of #302.

**Closed by shawnacscott** 2015-03-22 06:09 UTC
