### ISSUE TITLE
Uptick in spam

### ISSUE THREAD

**Issue by turoczy** [calagator/calagator#696] opened 2022-04-25 13:54 UTC
Not sure that this is a "bug" per se, but we've seen a noticeable uptick in spam making it into the RSS feed as of late. Not sure if there's anything to be done beyond the captcha measures already in place. I just wanted to make a note of it.

**Comment by reidab** [comment] 2022-05-20 05:47
👋 hi Rick —

I've spun out a discussion here https://github.com/calagator/calagator/discussions/701 with all the history of what we've tried and other ideas I know about. Let's see if we can figure out something with our current tools or a different direction.

Closing this, since it's not a bug, but want to keep this going.

**Comment by reidab** [comment] 2022-05-20 05:47
👋 hi Rick —

I've spun out a discussion here https://github.com/calagator/calagator/discussions/701 with all the history of what we've tried and other ideas I know about. Let's see if we can figure out something with our current tools or a different direction.

Closing this, since it's not a bug, but want to keep this going.

**Closed by reidab** 2022-05-20 05:47 UTC

**Comment by turoczy** [comment] 2022-05-20 14:22
Thanks @reidab! I'll read through it. 

I appreciate there's a difficult balance here. I'm just hopeful that we can restore the Portland instance to its previous utility for the community. And the spam stuff has been running counter to that, to be sure.

Again, appreciate the consideration and thoughtfulness.
