### ISSUE TITLE
Unable to import a meetup event. Reports a 404 error

### ISSUE THREAD

**Issue by NickSchimek** [calagator/calagator#651] opened 2020-11-12 00:40 UTC
The following error is returned when trying to import this meetup event: https://www.meetup.com/Code-for-PDX/events/hzksxrybcqbmb/
```
ERROR: Unable to import: Unknown error: 404 Not Found
```

**Comment by aeschright** [comment] 2021-12-10 23:16
Thanks for reporting this! The meetup API endpoint we were using is no longer available, so we'll need to update to the new one. In the meantime I can set up a fallback to use the iCalendar option.

**Comment by aeschright** [comment] 2021-12-22 23:38
Closing as duplicate of #593

**Closed by aeschright** 2021-12-22 23:38 UTC
