### ISSUE TITLE
Un-deletable venues

### ISSUE THREAD

**Issue by akf** [calagator/calagator#373] opened 2015-05-27 23:39 UTC
Calagator.org currently has two spammy venues that do not show any associated events and yet, when one tries to delete them, the error message "ERROR: Cannot destroy venue that has associated events, you must reassociate all its events first." is displayed and the venue is not deleted. 

This probably indicates a problem in the code somewhere. I was able to delete several other spammy venues today, so it's something specific about these venues:

http://calagator.org/venues/202394962
http://calagator.org/venues/202394960

**Comment by shawnacscott** [comment] 2015-05-29 19:28
Thanks for the report!

This looks to me like a duplicate of #207. @akf, can you check it out and see if it looks like the same issue to you?

**Comment by akf** [comment] 2015-05-29 19:40
Yes, it certainly does look like the same issue. Might I suggest leaving these two venues in place for forensics? It would probably be fine to edit the spam out (I already edited one of them quite a bit, clearing out fields, in case one of the non-required fields was triggering the problem). 

This is something I'd be interested in digging into at a future code sprint, if someone else doesn't get to it first. I'm not particularly familiar with the Calagator code base, but this kind of bug is how I tend to learn. I'd want to pair with someone who could inspect the database.

**Comment by akf** [comment] 2015-05-29 19:41
(Hm, does github issues not have a "mark as duplicate" function? Close this if you think that's appropriate. Thanks!

**Comment by shawnacscott** [comment] 2015-05-29 19:54
yeah, no duplicate function, unfortunately. Next code sprint is a week from tomorrow on June 6th at Lucky Lab. If you're available, we'd love to have you come!

**Closed by shawnacscott** 2015-05-29 19:54 UTC
